version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - moonoz-network

  app:
    build: .
    container_name: springboot-app
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/moonoz?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    depends_on:
      - redis
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - moonoz-network

networks:
  moonoz-network:
    driver: bridge